### PR TITLE
systemd: add sandboxing options

### PR DESCRIPTION
**Pull request by mmilata**
Adds some [systemd sandboxing options](https://www.freedesktop.org/software/systemd/man/systemd.exec.html) to the service file. Ported from NixOS/nixpkgs#74700. Might be good idea to test it some more before merging:)

### CODE REVIEW

**Comment by Mic92** [comment]
If this goes through, it might be a good idea to also use the unit file directly in the NixOS module.

**Comment by DanielAdolfsson** [comment]
Cool! Although, I'm not accepting new PRs to the 0.x branch. Working on a complete rewrite under branch `1.0-devel`. It's not ready yet, but I would accept a PR for this fix to that branch.

**Comment by mmilata** [comment]
I suck at using github and accidentally closed this when trying to change base branch to `1.0-devel`. Please see #59 for another attempt.

@Mic92 do you mean for the NixOS module to install unit file from upstream sources instead of generating one? Do you know of other modules that do it? We'd have to inject the path to the binary somehow and also change the unit type `forking` -> `simple`.

**Comment by Mic92** [comment]
@mmilata You can override unit description from nixos configuration. Have a look at the nfs module. It uses `systemd.packages` to add the systemd units and than just overrides selective options using the normal systemd service options.

**Pull request closed without merging**
