### PR TITLE
ndppd.service

### PR DESCRIPTION
**Pull request by florianl**
Add a basic systemd service file

### CODE REVIEW

**Comment by meeuw** [comment]
I've crafted this systemd service file for Fedora:
https://github.com/meeuw/fedora-ndppd/blob/master/ndppd.service
```[Unit]
Description=NDP Proxy Daemon
After=network.target

[Service]
ExecStart=/usr/sbin/ndppd -d -p /var/run/ndppd/ndppd.pid
Type=forking
PIDFile=/var/run/ndppd/ndppd.pid

[Install]
WantedBy=multi-user.target
```

**Comment by florianl** [comment]
Would be great to get it upstream.

**Comment by DanielAdolfsson** [comment]
I suppose you mean @meeuw's? Anyone like to submit a new pull request in that case?

**Comment by florianl** [comment]
Yes - I'm talking about @meeuw systemd file. It's better, than mine.

**Comment by fansari** [comment]
Sorry, but it does not work.
[root@frank-router ~]# journalctl -f -u ndppd
-- Logs begin at Mon 2017-05-15 13:36:10 CEST. --
May 17 10:09:58 frank-router.localdomain ndppd[7874]: (notice) ndppd (NDP Proxy Daemon) version 0.2.4
May 17 10:09:58 frank-router.localdomain ndppd[7874]: (notice) Using configuration file '/etc/ndppd.conf'
May 17 10:09:58 frank-router.localdomain ndppd[7875]: (error) Shutting down...
May 17 10:09:58 frank-router.localdomain ndppd[7875]: (notice) Bye
May 17 10:10:16 frank-router.localdomain systemd[1]: Starting NDP Proxy Daemon...
May 17 10:10:16 frank-router.localdomain ndppd[7913]: (notice) ndppd (NDP Proxy Daemon) version 0.2.4
May 17 10:10:16 frank-router.localdomain ndppd[7913]: (notice) Using configuration file '/etc/ndppd.conf'
May 17 10:10:16 frank-router.localdomain systemd[1]: PID file /var/run/ndppd/ndppd.pid not readable (yet?) after start.
May 17 10:11:21 frank-router.localdomain systemd[1]: [/etc/systemd/system/ndppd.service:1] Assignment outside of section. Ignoring.
May 17 10:11:21 frank-router.localdomain systemd[1]: [/etc/systemd/system/ndppd.service:2] Assignment outside of section. Ignoring.

**Comment by DanielAdolfsson** [comment]
Merged the other one. Thanks guys!

**Comment by fansari** [comment]
I suggest this:

<
[Unit]
Description=NDP Proxy Daemon
After=network.target

[Service]
Type=forking
ExecStartPre=/usr/bin/mkdir -p /var/run/ndppd
ExecStart=/usr/local/sbin/ndppd -d -p /var/run/ndppd/ndppd.pid
PIDFile=/var/run/ndppd/ndppd.pid

[Install]
WantedBy=multi-user.target
>

**Comment by meeuw** [comment]
I think it would be better to add this to the `install` target of `Makefile`

**Comment by fansari** [comment]
Sorry, this is unclear to me. What do you mean? The creation of the /var/run/ndppd directory or the service file itself? I mean /var/run is a symlink to /run. The content of /run is created dynamically on tmpfs so this has not to do with the installation.

**Comment by meeuw** [comment]
Hi @fansari you are right, but the solution needs to be different (I'm looking at radvd how this is done).

For systemd a file needs to be added: `/usr/lib/tmpfiles.d/ndppd.conf` with the following contents:
```
d	/var/run/ndppd	0755 ndppd ndppd
```

Do you agree?

**Comment by fansari** [comment]
Well, for me I guess it should be because I don't have user and group ndppd.

```
d	/var/run/ndppd	0755 root root
```
I tried this but the directory /var/run/ndppd is not created so the systemctl start command is hanging. What am I doing wrong?

**Comment by SpareSimian** [comment]
Why is this forking? The PID file gets created by the daemon process so systemd complains that it doesn't exist yet when its foreground process exits. Better to use a Type=simple and drop all the arguments.

**Comment by meeuw** [comment]
@SpareSimian I think I used the service file from radvd as a template. See https://github.com/DanielAdolfsson/ndppd/pull/28

I think the advantage of forking is that the process has a way to inform systemd that it started and is ready for service.

If you use simple there is no way for systemd to know that the service is ready for service and depending services can be started.

But that doesn't matter very much for ndppd (I guess) so Type=simple might make sense.

It sounds like you've found a bug with the PID file, I don't remember having this problem.

**Comment by SpareSimian** [comment]
The PID file creation issue is a race condition. You might not see it if the forked process gets to run long enough to create the PID file before systemd gets to run to look for it. A fast system with lots of cores would allow systemd to run as soon as the foreground process exits and see the missing PID file. The PID file needs to be created by the foreground process before it exits, using the return value from fork(). 

In ndppd.cc, move the code that creates the PID file at line 364 to demonize() at line 44, before the call to exit().

**Pull request closed without merging**
